//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuto.DataLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à am.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponible le ....
        /// </summary>
        public static string AvailableAt {
            get {
                return ResourceManager.GetString("AvailableAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos modifications ont été sauvegardées avec success!.
        /// </summary>
        public static string ChangesHaveBeenSaved {
            get {
                return ResourceManager.GetString("ChangesHaveBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation des changements.
        /// </summary>
        public static string DisplayAccountEditConfirmChanges {
            get {
                return ResourceManager.GetString("DisplayAccountEditConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour confirmer les changements, entrez votre courriel ainsi que votre mot de passe actuel..
        /// </summary>
        public static string DisplayAccountEditConfirmChangesHelp {
            get {
                return ResourceManager.GetString("DisplayAccountEditConfirmChangesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre adresse courriel actuelle.
        /// </summary>
        public static string DisplayAccountEditCurrentEmail {
            get {
                return ResourceManager.GetString("DisplayAccountEditCurrentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre addresse.
        /// </summary>
        public static string DisplayAccountEditCurrentEmailConfirm {
            get {
                return ResourceManager.GetString("DisplayAccountEditCurrentEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe actuel.
        /// </summary>
        public static string DisplayAccountEditCurrentPassword {
            get {
                return ResourceManager.GetString("DisplayAccountEditCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre mot de passe actuel.
        /// </summary>
        public static string DisplayAccountEditCurrentPasswordConfirm {
            get {
                return ResourceManager.GetString("DisplayAccountEditCurrentPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre mot de passe.
        /// </summary>
        public static string DisplayAccountEditEnterCurrentPassword {
            get {
                return ResourceManager.GetString("DisplayAccountEditEnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom complet.
        /// </summary>
        public static string DisplayAccountEditFullName {
            get {
                return ResourceManager.GetString("DisplayAccountEditFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez votre adresse courriel ainsi que sa confirmation pour la modifier.
        /// </summary>
        public static string DisplayAccountEditHelpBlockNewEmail {
            get {
                return ResourceManager.GetString("DisplayAccountEditHelpBlockNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle addresse courriel.
        /// </summary>
        public static string DisplayAccountEditNewEmail {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez .
        /// </summary>
        public static string DisplayAccountEditNewEmailConfirm {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez la nouvelle adresse courriel.
        /// </summary>
        public static string DisplayAccountEditNewEmailConfirmHelp {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewEmailConfirmHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de famille.
        /// </summary>
        public static string DisplayAccountEditNewLastName {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string DisplayAccountEditNewName {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau mot de passe.
        /// </summary>
        public static string DisplayAccountEditNewPassword {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez le nouveau mot de passe.
        /// </summary>
        public static string DisplayAccountEditNewPasswordConfirmHelp {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewPasswordConfirmHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez un nouveau mot de passe.
        /// </summary>
        public static string DisplayAccountEditNewPasswordHelp {
            get {
                return ResourceManager.GetString("DisplayAccountEditNewPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez nouveau mot de passe.
        /// </summary>
        public static string DisplayAccountNewPasswordConfirm {
            get {
                return ResourceManager.GetString("DisplayAccountNewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du cours.
        /// </summary>
        public static string DisplayCourseName {
            get {
                return ResourceManager.GetString("DisplayCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, il semble que la page que vous tentez d&apos;accèder n&apos;existe pas ou a changé d&apos;emplacement. Si le problème persiste, veuillez contacter le support technique..
        /// </summary>
        public static string DisplayError404Description {
            get {
                return ResourceManager.GetString("DisplayError404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whoops!.
        /// </summary>
        public static string DisplayError404Title {
            get {
                return ResourceManager.GetString("DisplayError404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, il semble y avoir eu une erreur au niveau du serveur. Veuillez réessayer ou contacter le support technique..
        /// </summary>
        public static string DisplayError500Description {
            get {
                return ResourceManager.GetString("DisplayError500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whoops!.
        /// </summary>
        public static string DisplayError500Title {
            get {
                return ResourceManager.GetString("DisplayError500Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les séances de tutorat de groupe.
        /// </summary>
        public static string DisplayGroupSessionDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayGroupSessionDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances de groupe.
        /// </summary>
        public static string DisplayGroupSessionMenuItem {
            get {
                return ResourceManager.GetString("DisplayGroupSessionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tuteur.
        /// </summary>
        public static string DisplayGroupSessionTutorName {
            get {
                return ResourceManager.GetString("DisplayGroupSessionTutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aidé.
        /// </summary>
        public static string DisplayHelped {
            get {
                return ResourceManager.GetString("DisplayHelped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres commentaires.
        /// </summary>
        public static string DisplayHelpRequestComments {
            get {
                return ResourceManager.GetString("DisplayHelpRequestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours dans lequel vous avez de la difficulté.
        /// </summary>
        public static string DisplayHelpRequestCourse {
            get {
                return ResourceManager.GetString("DisplayHelpRequestCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du cours.
        /// </summary>
        public static string DisplayHelpRequestCourseName {
            get {
                return ResourceManager.GetString("DisplayHelpRequestCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de création.
        /// </summary>
        public static string DisplayHelpRequestCreatedTime {
            get {
                return ResourceManager.GetString("DisplayHelpRequestCreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date/Heure.
        /// </summary>
        public static string DisplayHelpRequestDateTime {
            get {
                return ResourceManager.GetString("DisplayHelpRequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes demandes d&apos;aide.
        /// </summary>
        public static string DisplayHelpRequestDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayHelpRequestDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;aidé.
        /// </summary>
        public static string DisplayHelpRequestHelpedName {
            get {
                return ResourceManager.GetString("DisplayHelpRequestHelpedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes d&apos;aide.
        /// </summary>
        public static string DisplayHelpRequestMenuItem {
            get {
                return ResourceManager.GetString("DisplayHelpRequestMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notions mal comprises.
        /// </summary>
        public static string DisplayHelpRequestMisunderstoodNotions {
            get {
                return ResourceManager.GetString("DisplayHelpRequestMisunderstoodNotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivi.
        /// </summary>
        public static string DisplayHelpRequestReport {
            get {
                return ResourceManager.GetString("DisplayHelpRequestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de la séance.
        /// </summary>
        public static string DisplayHelpRequestSessionDate {
            get {
                return ResourceManager.GetString("DisplayHelpRequestSessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endroit de la séance.
        /// </summary>
        public static string DisplayHelpRequestSessionPlace {
            get {
                return ResourceManager.GetString("DisplayHelpRequestSessionPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        public static string DisplayHelpRequestState {
            get {
                return ResourceManager.GetString("DisplayHelpRequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tuteur.
        /// </summary>
        public static string DisplayHelpRequestTutorName {
            get {
                return ResourceManager.GetString("DisplayHelpRequestTutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon tableau de bord.
        /// </summary>
        public static string DisplayHomeDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayHomeDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string DisplayHomeMenuItem {
            get {
                return ResourceManager.GetString("DisplayHomeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes séances de tutorat assignées.
        /// </summary>
        public static string DisplayIndividualSessionDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayIndividualSessionDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les demandes d&apos;aide à confirmer, confirmées et terminées.
        /// </summary>
        public static string DisplayIndividualSessionManagerDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayIndividualSessionManagerDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes d&apos;aide.
        /// </summary>
        public static string DisplayIndividualSessionManagerMenuItem {
            get {
                return ResourceManager.GetString("DisplayIndividualSessionManagerMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances assignées.
        /// </summary>
        public static string DisplayIndividualSessionMenuItem {
            get {
                return ResourceManager.GetString("DisplayIndividualSessionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrateur.
        /// </summary>
        public static string DisplayManager {
            get {
                return ResourceManager.GetString("DisplayManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun suivi.
        /// </summary>
        public static string DisplayNoReportAvailable {
            get {
                return ResourceManager.GetString("DisplayNoReportAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string DisplaySessionDate {
            get {
                return ResourceManager.GetString("DisplaySessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu.
        /// </summary>
        public static string DisplaySessionPlace {
            get {
                return ResourceManager.GetString("DisplaySessionPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps.
        /// </summary>
        public static string DisplaySessionTemps {
            get {
                return ResourceManager.GetString("DisplaySessionTemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure.
        /// </summary>
        public static string DisplaySessionTime {
            get {
                return ResourceManager.GetString("DisplaySessionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuteur.
        /// </summary>
        public static string DisplayTutor {
            get {
                return ResourceManager.GetString("DisplayTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponible pour le tutorat de groupe.
        /// </summary>
        public static string DisplayTutorAvailableForGroupSession {
            get {
                return ResourceManager.GetString("DisplayTutorAvailableForGroupSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponible pour le tutorat individuel.
        /// </summary>
        public static string DisplayTutorAvailableForIndividualSession {
            get {
                return ResourceManager.GetString("DisplayTutorAvailableForIndividualSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours.
        /// </summary>
        public static string DisplayTutorHelpRequestCourse {
            get {
                return ResourceManager.GetString("DisplayTutorHelpRequestCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom complet de l&apos;aidé.
        /// </summary>
        public static string DisplayTutorHelpRequestEntryHelpedFullName {
            get {
                return ResourceManager.GetString("DisplayTutorHelpRequestEntryHelpedFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endroit prévu.
        /// </summary>
        public static string DisplayTutorHelpRequestEntryPlace {
            get {
                return ResourceManager.GetString("DisplayTutorHelpRequestEntryPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date renconte prévue.
        /// </summary>
        public static string DisplayTutorHelpRequestExpectedDate {
            get {
                return ResourceManager.GetString("DisplayTutorHelpRequestExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string DisplayTutorLastName {
            get {
                return ResourceManager.GetString("DisplayTutorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les tuteurs et leur statut.
        /// </summary>
        public static string DisplayTutorListDescriptionMenuItem {
            get {
                return ResourceManager.GetString("DisplayTutorListDescriptionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des tuteurs.
        /// </summary>
        public static string DisplayTutorListMenuItem {
            get {
                return ResourceManager.GetString("DisplayTutorListMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string DisplayTutorName {
            get {
                return ResourceManager.GetString("DisplayTutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        public static string DisplayTutorState {
            get {
                return ResourceManager.GetString("DisplayTutorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre d&apos;heures travaillées.
        /// </summary>
        public static string DisplayTutorWorkedHours {
            get {
                return ResourceManager.GetString("DisplayTutorWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez votre mot de passe.
        /// </summary>
        public static string DisplayUserConfirmPassword {
            get {
                return ResourceManager.GetString("DisplayUserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string DisplayUserLastName {
            get {
                return ResourceManager.GetString("DisplayUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse courriel.
        /// </summary>
        public static string DisplayUserMail {
            get {
                return ResourceManager.GetString("DisplayUserMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string DisplayUserName {
            get {
                return ResourceManager.GetString("DisplayUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string DisplayUserPassword {
            get {
                return ResourceManager.GetString("DisplayUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le cours que vous avez choisi est invalide !.
        /// </summary>
        public static string ErrorCreateHelpRequest {
            get {
                return ResourceManager.GetString("ErrorCreateHelpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse courriel ou mot de passe courant invalide..
        /// </summary>
        public static string ErrorEditWrongCurrentInfo {
            get {
                return ResourceManager.GetString("ErrorEditWrongCurrentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date doit être dans le format (aaaa-mm-jj)..
        /// </summary>
        public static string ErrorGroupSessionDateFormat {
            get {
                return ResourceManager.GetString("ErrorGroupSessionDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure doit être dans le format (hh:mm)..
        /// </summary>
        public static string ErrorGroupSessionTimeFormat {
            get {
                return ResourceManager.GetString("ErrorGroupSessionTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un cours dans lequel vous avez de la difficulté..
        /// </summary>
        public static string ErrorHelpRequestCourseRequired {
            get {
                return ResourceManager.GetString("ErrorHelpRequestCourseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;horaire entrée est invalide..
        /// </summary>
        public static string ErrorHelpRequestInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorHelpRequestInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier les notions mals comprises..
        /// </summary>
        public static string ErrorHelpRequestMisunderstoodNotionsRequired {
            get {
                return ResourceManager.GetString("ErrorHelpRequestMisunderstoodNotionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier votre horaire..
        /// </summary>
        public static string ErrorHelpRequestSchedule {
            get {
                return ResourceManager.GetString("ErrorHelpRequestSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauvais nom d&apos;utilisateur / mot de passe.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le message doit être de 200 caractères au plus..
        /// </summary>
        public static string ErrorReportMessageMaxLenght {
            get {
                return ResourceManager.GetString("ErrorReportMessageMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un message sur le déroulement de votre séance..
        /// </summary>
        public static string ErrorReportMessageRequired {
            get {
                return ResourceManager.GetString("ErrorReportMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s’est produite lors du traitement de la requête..
        /// </summary>
        public static string ErrorRequest {
            get {
                return ResourceManager.GetString("ErrorRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;heure d&apos;un bloc d&apos;horaire doit être entre 8h et 17h..
        /// </summary>
        public static string ErrorScheduleBlockLength {
            get {
                return ResourceManager.GetString("ErrorScheduleBlockLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date doit être dans le format (AAAA-MM-JJ HH-MM-SS)..
        /// </summary>
        public static string ErrorSessionDateFormat {
            get {
                return ResourceManager.GetString("ErrorSessionDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier la date de la séance..
        /// </summary>
        public static string ErrorSessionDateRequired {
            get {
                return ResourceManager.GetString("ErrorSessionDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un lieux pour la séance..
        /// </summary>
        public static string ErrorSessionPlaceRequired {
            get {
                return ResourceManager.GetString("ErrorSessionPlaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier l&apos;heure de la séance de groupe..
        /// </summary>
        public static string ErrorSessionTimeRequired {
            get {
                return ResourceManager.GetString("ErrorSessionTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir au moins un type de tutorat..
        /// </summary>
        public static string ErrorTutorAvailableAtLeastOne {
            get {
                return ResourceManager.GetString("ErrorTutorAvailableAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez avoir des aptitudes dans au moins un cours..
        /// </summary>
        public static string ErrorTutorCourseSkillsRequired {
            get {
                return ResourceManager.GetString("ErrorTutorCourseSkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il n&apos;y a pas de demande d&apos;aide avec un suivi à remplir..
        /// </summary>
        public static string ErrorTutorReportNoHelpRequestsToDo {
            get {
                return ResourceManager.GetString("ErrorTutorReportNoHelpRequestsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il faut choisir une demande d&apos;aide afin de soumettre un suivi..
        /// </summary>
        public static string ErrorTutorReportRequiredId {
            get {
                return ResourceManager.GetString("ErrorTutorReportRequiredId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les courriels ne concordent pas. Veuillez réessayer..
        /// </summary>
        public static string ErrorUserConfirmEmail {
            get {
                return ResourceManager.GetString("ErrorUserConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les mots de passe ne concordent pas. Veuillez réessayer..
        /// </summary>
        public static string ErrorUserConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorUserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un nom..
        /// </summary>
        public static string ErrorUserLastNameRequired {
            get {
                return ResourceManager.GetString("ErrorUserLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauvaise adresse courriel ou mot de passe, veuillez réessayer..
        /// </summary>
        public static string ErrorUserLoginWrongCredentials {
            get {
                return ResourceManager.GetString("ErrorUserLoginWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier une adresse courriel..
        /// </summary>
        public static string ErrorUserMailRequired {
            get {
                return ResourceManager.GetString("ErrorUserMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse courriel spécifiée semble déjà être utilisée, veuillez réessayer..
        /// </summary>
        public static string ErrorUserMailUnique {
            get {
                return ResourceManager.GetString("ErrorUserMailUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier une adresse courriel valide..
        /// </summary>
        public static string ErrorUserMailValid {
            get {
                return ResourceManager.GetString("ErrorUserMailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un prénom..
        /// </summary>
        public static string ErrorUserNameRequired {
            get {
                return ResourceManager.GetString("ErrorUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe doit être de 6 caractères ou plus..
        /// </summary>
        public static string ErrorUserPasswordMinimum {
            get {
                return ResourceManager.GetString("ErrorUserPasswordMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier un mot de passe..
        /// </summary>
        public static string ErrorUserPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez avoir au moins un bloc horaire de disponible..
        /// </summary>
        public static string ErrorUserScheduleBlockRequired {
            get {
                return ResourceManager.GetString("ErrorUserScheduleBlockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez spécifier votre horaire..
        /// </summary>
        public static string ErrorUserScheduleRequired {
            get {
                return ResourceManager.GetString("ErrorUserScheduleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vendredi.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner d&apos;autre plage horaire pour réessayer..
        /// </summary>
        public static string HelpRequestMgrAssignAutomaticNoAvailableTutorsText {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignAutomaticNoAvailableTutorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun tuteur n&apos;est disponible à cette plage horaire !.
        /// </summary>
        public static string HelpRequestMgrAssignAutomaticNoAvailableTutorsTitle {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignAutomaticNoAvailableTutorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection automatique d&apos;un tuteur :.
        /// </summary>
        public static string HelpRequestMgrAssignAutomaticSelection {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignAutomaticSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez sur une case horaire pour obtenir la liste des tuteurs disponible à cette même place horaire..
        /// </summary>
        public static string HelpRequestMgrAssignAutomaticSelectionText {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignAutomaticSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assigner le tuteur à la demande d&apos;aide.
        /// </summary>
        public static string HelpRequestMgrAssignBtn {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le tuteur à assigner parmis les &lt;span class=&quot;numTutor&quot;&gt;&lt;/span&gt; de la liste suivante :.
        /// </summary>
        public static string HelpRequestMgrAssignChooseTutorFromList {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignChooseTutorFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires additionnels à la demande :.
        /// </summary>
        public static string HelpRequestMgrAssignComments {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez-vous l&apos;assignation suivante ?.
        /// </summary>
        public static string HelpRequestMgrAssignConfirmModal {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignConfirmModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui, assigner la demande.
        /// </summary>
        public static string HelpRequestMgrAssignConfirmModalBtnAccept {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignConfirmModalBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez-vous l&apos;assignation du tuteur &lt;span id=&quot;tutorName&quot;&gt;&lt;/span&gt; pour la demande d&apos;aide effectuée par &lt;span id=&quot;helpedName&quot;&gt;&lt;/span&gt; ?&lt;br /&gt;&lt;br/&gt; 
        ///Si le tuteur et l&apos;aidé confirment leur présence, la rencontre individuelle aura lieu dans le local &lt;span id=&quot;localName&quot;&gt;&lt;/span&gt; le &lt;span id=&quot;sessionFullDate&quot;&gt;&lt;/span&gt; de &lt;span id=&quot;sessionHourStart&quot;&gt;&lt;/span&gt;h à &lt;span id=&quot;sessionHourEnd&quot;&gt;&lt;/span&gt;h..
        /// </summary>
        public static string HelpRequestMgrAssignConfirmModalText {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignConfirmModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours en difficulté.
        /// </summary>
        public static string HelpRequestMgrAssignCourseName {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez spécifier un local où aura lieu la rencontre individuelle.
        /// </summary>
        public static string HelpRequestMgrAssignEmptyLocalName {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignEmptyLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;aidé.
        /// </summary>
        public static string HelpRequestMgrAssignHelpedName {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignHelpedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails de la demande d&apos;aide.
        /// </summary>
        public static string HelpRequestMgrAssignHelpRequestDetails {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignHelpRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectonner une heure de fin entre 16h et 18h.
        /// </summary>
        public static string HelpRequestMgrAssignInvalidEndHour {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignInvalidEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La demande d&apos;aide spécifiée n&apos;est pas valide... veuillez réessayer.
        /// </summary>
        public static string HelpRequestMgrAssignInvalidHelpRequestId {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignInvalidHelpRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner une heure de début entre 8h et 16h.
        /// </summary>
        public static string HelpRequestMgrAssignInvalidStartHour {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignInvalidStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le tuteur spécifié n&apos;est pas valide... veuillez réessayer.
        /// </summary>
        public static string HelpRequestMgrAssignInvalidTutorId {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignInvalidTutorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local assigné.
        /// </summary>
        public static string HelpRequestMgrAssignLocalName {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuteur assigné :.
        /// </summary>
        public static string HelpRequestMgrAssignManualAssignedTutor {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignManualAssignedTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -- Choisir un tuteur --.
        /// </summary>
        public static string HelpRequestMgrAssignManualAssignedTutorSelectionDefault {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignManualAssignedTutorSelectionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez à tout moment sélectionner manuellement un tuteur à partir de la liste ci-dessous..
        /// </summary>
        public static string HelpRequestMgrAssignManualSelectionText {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignManualSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection manuel d&apos;un tuteur :.
        /// </summary>
        public static string HelpRequestMgrAssignManualSelectionTitle {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignManualSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notions mal comprises.
        /// </summary>
        public static string HelpRequestMgrAssignMisunderstoodNotions {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignMisunderstoodNotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heures ce mois-ci.
        /// </summary>
        public static string HelpRequestMgrAssignMonthlyHours {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignMonthlyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vous assurer que la date de la séance selon votre configuration est postérieure à celle d&apos;aujourd&apos;hui..
        /// </summary>
        public static string HelpRequestMgrAssignNotAFutureDate {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignNotAFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  tuteurs sont disponibles à cette plage horaire.
        /// </summary>
        public static string HelpRequestMgrAssignNumTutorsAvailableAtPlural {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignNumTutorsAvailableAtPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  tuteur est disponible à cette plage horaire.
        /// </summary>
        public static string HelpRequestMgrAssignNumTutorsAvailableAtSingular {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignNumTutorsAvailableAtSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;aide faite par {0} {1} le {2}.
        /// </summary>
        public static string HelpRequestMgrAssignPageTitle {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assignation d&apos;un tuteur.
        /// </summary>
        public static string HelpRequestMgrAssignTutorTitle {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignTutorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilitées de {0} {1}.
        /// </summary>
        public static string HelpRequestMgrAssignUserDisponibilities {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignUserDisponibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Semaine du ....
        /// </summary>
        public static string HelpRequestMgrAssignWeekPick {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignWeekPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir des dates valides pour la sélection de la semaine.
        /// </summary>
        public static string HelpRequestMgrAssignWeekPickInvalidFormat {
            get {
                return ResourceManager.GetString("HelpRequestMgrAssignWeekPickInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration des demandes d&apos;aide.
        /// </summary>
        public static string HelpRequestMgrPagesTitle {
            get {
                return ResourceManager.GetString("HelpRequestMgrPagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complété.
        /// </summary>
        public static string HelpRequestRepportFilledOut {
            get {
                return ResourceManager.GetString("HelpRequestRepportFilledOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faire.
        /// </summary>
        public static string HelpRequestRepportFillOut {
            get {
                return ResourceManager.GetString("HelpRequestRepportFillOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non disponible.
        /// </summary>
        public static string HelpRequestRepportNotAvailable {
            get {
                return ResourceManager.GetString("HelpRequestRepportNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string ListEntryActions {
            get {
                return ResourceManager.GetString("ListEntryActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string LoginPartialLine1 {
            get {
                return ResourceManager.GetString("LoginPartialLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string LoginPartialLine2 {
            get {
                return ResourceManager.GetString("LoginPartialLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string ManagerHelpRequestConsult {
            get {
                return ResourceManager.GetString("ManagerHelpRequestConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre profil.
        /// </summary>
        public static string MenuAccount1 {
            get {
                return ResourceManager.GetString("MenuAccount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        public static string MenuAccount2 {
            get {
                return ResourceManager.GetString("MenuAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lundi.
        /// </summary>
        public static string Moday {
            get {
                return ResourceManager.GetString("Moday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rapports des heures travaillées par tuteur.
        /// </summary>
        public static string MonthlyWorkedHoursReportTitle {
            get {
                return ResourceManager.GetString("MonthlyWorkedHoursReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nbre. heures.
        /// </summary>
        public static string NumHoursMin {
            get {
                return ResourceManager.GetString("NumHoursMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pm.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre inscription a bien été reçue. Vous pouvez maintenant utiliser votre identifiant et votre mot de passe. Veuillez ne pas répondre à ce message. Merci..
        /// </summary>
        public static string SendConfirmationEmailBody {
            get {
                return ResourceManager.GetString("SendConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de votre inscription à Tuto.
        /// </summary>
        public static string SendConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("SendConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le responsable a refusé votre inscription en tant que tuteur. La raison est la suivante : .
        /// </summary>
        public static string SendReasonEmailBody {
            get {
                return ResourceManager.GetString("SendReasonEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refus de votre inscription en tant que Tuteur..
        /// </summary>
        public static string SendReasonEmailSubject {
            get {
                return ResourceManager.GetString("SendReasonEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bilan.
        /// </summary>
        public static string StateStringBilan {
            get {
                return ResourceManager.GetString("StateStringBilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmé.
        /// </summary>
        public static string StateStringConfirmed {
            get {
                return ResourceManager.GetString("StateStringConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminée.
        /// </summary>
        public static string StateStringFinished {
            get {
                return ResourceManager.GetString("StateStringFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non assignée.
        /// </summary>
        public static string StateStringNotAssigned {
            get {
                return ResourceManager.GetString("StateStringNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À confirmer.
        /// </summary>
        public static string StateStringToBeConfirmed {
            get {
                return ResourceManager.GetString("StateStringToBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un language vraiment compliquer....
        /// </summary>
        public static string TestDataHelpRequestComment {
            get {
                return ResourceManager.GetString("TestDataHelpRequestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il ressemble à un diamand?.
        /// </summary>
        public static string TestDataHelpRequestComment2 {
            get {
                return ResourceManager.GetString("TestDataHelpRequestComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C++.
        /// </summary>
        public static string TestDataHelpRequestMisunderstoodNotions {
            get {
                return ResourceManager.GetString("TestDataHelpRequestMisunderstoodNotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruby.
        /// </summary>
        public static string TestDataHelpRequestMisunderstoodNotions2 {
            get {
                return ResourceManager.GetString("TestDataHelpRequestMisunderstoodNotions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [{\&quot;start\&quot;:\&quot;08:00 am\&quot;,\&quot;end\&quot;:\&quot;10:00 am\&quot;,\&quot;day\&quot;:1}].
        /// </summary>
        public static string TestDataHelpRequestScheduleJson {
            get {
                return ResourceManager.GetString("TestDataHelpRequestScheduleJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [{\&quot;start\&quot;:\&quot;10:00 am\&quot;,\&quot;end\&quot;:\&quot;12:00 pm\&quot;,\&quot;day\&quot;:1}].
        /// </summary>
        public static string TestDataHelpRequestScheduleJson2 {
            get {
                return ResourceManager.GetString("TestDataHelpRequestScheduleJson2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un suivi super-cool de l&apos;aide..
        /// </summary>
        public static string TestDataIndividualSessionHelpedMessage {
            get {
                return ResourceManager.GetString("TestDataIndividualSessionHelpedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un suivi super-cool du tuteur..
        /// </summary>
        public static string TestDataIndividualSessionTutorMessage {
            get {
                return ResourceManager.GetString("TestDataIndividualSessionTutorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeudi.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mardi.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom du tuteur.
        /// </summary>
        public static string TutorFirstName {
            get {
                return ResourceManager.GetString("TutorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tuteur.
        /// </summary>
        public static string TutorLastName {
            get {
                return ResourceManager.GetString("TutorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du tuteur.
        /// </summary>
        public static string TutorName {
            get {
                return ResourceManager.GetString("TutorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heures travailées.
        /// </summary>
        public static string TutorWorkedHours {
            get {
                return ResourceManager.GetString("TutorWorkedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez être connecté pour pouvoir accéder à cette page !.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez été assigné à une séance de tutorat individuelle le.
        /// </summary>
        public static string ViewAlertBody1 {
            get {
                return ResourceManager.GetString("ViewAlertBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à suite à une demande d&apos;aide effectuée par.
        /// </summary>
        public static string ViewAlertBody2 {
            get {
                return ResourceManager.GetString("ViewAlertBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rendez-vous dans vos demandes assignées pour confirmer ou non votre présence..
        /// </summary>
        public static string ViewAlertBody3 {
            get {
                return ResourceManager.GetString("ViewAlertBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez un bloc horaire dans le calendrier pour créer une séance de groupe..
        /// </summary>
        public static string ViewAlertInfo {
            get {
                return ResourceManager.GetString("ViewAlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assignation à une séance de tutorat individuelle.
        /// </summary>
        public static string ViewAssignedToHelpRequestHelpedPartialHeader {
            get {
                return ResourceManager.GetString("ViewAssignedToHelpRequestHelpedPartialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assignation d&apos;un tuteur.
        /// </summary>
        public static string ViewAssignPopupHeader {
            get {
                return ResourceManager.GetString("ViewAssignPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuteurs disponibles.
        /// </summary>
        public static string ViewAssignPopupLabel {
            get {
                return ResourceManager.GetString("ViewAssignPopupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        public static string ViewDetailsButton {
            get {
                return ResourceManager.GetString("ViewDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification de l&apos;horaire de la semaine prochaine des séances de groupe.
        /// </summary>
        public static string ViewEditCurrentScheduleHeader {
            get {
                return ResourceManager.GetString("ViewEditCurrentScheduleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification de l&apos;horaire par défaut des séances de groupe.
        /// </summary>
        public static string ViewEditDefaultScheduleHeader {
            get {
                return ResourceManager.GetString("ViewEditDefaultScheduleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre profil.
        /// </summary>
        public static string ViewEditHelpedHeader {
            get {
                return ResourceManager.GetString("ViewEditHelpedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre profil.
        /// </summary>
        public static string ViewEditManagerHeader {
            get {
                return ResourceManager.GetString("ViewEditManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre profil.
        /// </summary>
        public static string ViewEditTutorHeader {
            get {
                return ResourceManager.GetString("ViewEditTutorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer la recherche.
        /// </summary>
        public static string ViewFilter {
            get {
                return ResourceManager.GetString("ViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur | Gestion du tutorat Tuto.
        /// </summary>
        public static string ViewGeneralHeader {
            get {
                return ResourceManager.GetString("ViewGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à l&apos;accueil.
        /// </summary>
        public static string ViewGeneralReturnHome {
            get {
                return ResourceManager.GetString("ViewGeneralReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances de groupe.
        /// </summary>
        public static string ViewGroupSessionList1 {
            get {
                return ResourceManager.GetString("ViewGroupSessionList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances de groupe de la semaine prochaine.
        /// </summary>
        public static string ViewGroupSessionList2 {
            get {
                return ResourceManager.GetString("ViewGroupSessionList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assigner à un tuteur.
        /// </summary>
        public static string ViewGroupSessionListButton {
            get {
                return ResourceManager.GetString("ViewGroupSessionListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande à bel et bien été enregistrée !.
        /// </summary>
        public static string ViewHelpRequestCreateAlertSuccess {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une demande d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestCreateButton {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Important :.
        /// </summary>
        public static string ViewHelpRequestCreateControlGroup1 {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateControlGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaque rencontre est d&apos;une durée fixée à 2 heures..
        /// </summary>
        public static string ViewHelpRequestCreateControlGroup2 {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateControlGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faire une demande d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestCreateHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le cours dans lequel vous désirez obtenir de l&apos;aide.
        /// </summary>
        public static string ViewHelpRequestCreateHelpBlock {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreateHelpBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez les notions mal comprises ....
        /// </summary>
        public static string ViewHelpRequestCreatePlaceHolder1 {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreatePlaceHolder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez aussi préciser d&apos;autres informations nécessaires à votre demande.
        /// </summary>
        public static string ViewHelpRequestCreatePlaceHolder2 {
            get {
                return ResourceManager.GetString("ViewHelpRequestCreatePlaceHolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details de la demande d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestDetailsHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à la liste des demandes d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestDetailsReturnButton {
            get {
                return ResourceManager.GetString("ViewHelpRequestDetailsReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos demandes de tutorat.
        /// </summary>
        public static string ViewHelpRequestHelpedListHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestHelpedListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes d&apos;aide assignées.
        /// </summary>
        public static string ViewHelpRequestHelpedListLegend1 {
            get {
                return ResourceManager.GetString("ViewHelpRequestHelpedListLegend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les demandes d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestHelpedListLegend2 {
            get {
                return ResourceManager.GetString("ViewHelpRequestHelpedListLegend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration des demandes d&apos;aide.
        /// </summary>
        public static string ViewHelpRequestListHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes d&apos;aide à confirmer.
        /// </summary>
        public static string ViewHelpRequestListLegend1 {
            get {
                return ResourceManager.GetString("ViewHelpRequestListLegend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes d&apos;aide en cours et terminées.
        /// </summary>
        public static string ViewHelpRequestListLegend2 {
            get {
                return ResourceManager.GetString("ViewHelpRequestListLegend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soumettre.
        /// </summary>
        public static string ViewHelpRequestReportButton {
            get {
                return ResourceManager.GetString("ViewHelpRequestReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faire un suivi.
        /// </summary>
        public static string ViewHelpRequestReportHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandes de tutorat assignées.
        /// </summary>
        public static string ViewHelpRequestTutorListHeader {
            get {
                return ResourceManager.GetString("ViewHelpRequestTutorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ceci est le corps de l&apos;alerte, une fois cliquer sur le X, l&apos;alerte sera considérée comme vue..
        /// </summary>
        public static string ViewHomeIndexTaskBody {
            get {
                return ResourceManager.GetString("ViewHomeIndexTaskBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes tâches.
        /// </summary>
        public static string ViewHomeIndexTaskLegend {
            get {
                return ResourceManager.GetString("ViewHomeIndexTaskLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre de la tâche.
        /// </summary>
        public static string ViewHomeIndexTaskTitle {
            get {
                return ResourceManager.GetString("ViewHomeIndexTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue,.
        /// </summary>
        public static string ViewHomeIndexWelcome {
            get {
                return ResourceManager.GetString("ViewHomeIndexWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur interne est survenue. Le message n&apos;a pas été envoyé..
        /// </summary>
        public static string ViewInactivePopupAlert {
            get {
                return ResourceManager.GetString("ViewInactivePopupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pourquoi avez-vous refusé ce tuteur? Un message d&apos;explication lui sera envoyé par courriel..
        /// </summary>
        public static string ViewInactivePopupBody {
            get {
                return ResourceManager.GetString("ViewInactivePopupBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explications:.
        /// </summary>
        public static string ViewInactivePopupBodyExplication {
            get {
                return ResourceManager.GetString("ViewInactivePopupBodyExplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refus du tuteur.
        /// </summary>
        public static string ViewInactivePopupTitle {
            get {
                return ResourceManager.GetString("ViewInactivePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en tant qu&apos;aidé..
        /// </summary>
        public static string ViewLoginRegisterHelped {
            get {
                return ResourceManager.GetString("ViewLoginRegisterHelped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en tant que tuteur.
        /// </summary>
        public static string ViewLoginRegisterTutor {
            get {
                return ResourceManager.GetString("ViewLoginRegisterTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription en tant qu&apos;aidé.
        /// </summary>
        public static string ViewRegisterHelpedHeader {
            get {
                return ResourceManager.GetString("ViewRegisterHelpedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription en tant que tuteur.
        /// </summary>
        public static string ViewRegisterTutorHeader {
            get {
                return ResourceManager.GetString("ViewRegisterTutorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour pouvoir gérer les séances de groupe, vous devez d&apos;abord créer une horaire par défaut.
        /// </summary>
        public static string ViewScheduleAlertBlockBody {
            get {
                return ResourceManager.GetString("ViewScheduleAlertBlockBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention!.
        /// </summary>
        public static string ViewScheduleAlertBlockHeader {
            get {
                return ResourceManager.GetString("ViewScheduleAlertBlockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horaire par défaut.
        /// </summary>
        public static string ViewScheduleAlertInfo1 {
            get {
                return ResourceManager.GetString("ViewScheduleAlertInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour modifier l&apos;horaire par défaut,.
        /// </summary>
        public static string ViewScheduleAlertInfo2 {
            get {
                return ResourceManager.GetString("ViewScheduleAlertInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Horaire de la semaine prochaine.
        /// </summary>
        public static string ViewScheduleAlertInfo3 {
            get {
                return ResourceManager.GetString("ViewScheduleAlertInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour modifier l&apos;horaire de la semaine prochaine seulement,.
        /// </summary>
        public static string ViewScheduleAlertInfo4 {
            get {
                return ResourceManager.GetString("ViewScheduleAlertInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos modifications ont bien été sauvegardées..
        /// </summary>
        public static string ViewScheduleAlertSuccess {
            get {
                return ResourceManager.GetString("ViewScheduleAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de la séance de groupe.
        /// </summary>
        public static string ViewScheduleConfirmGroupSessionHeader {
            get {
                return ResourceManager.GetString("ViewScheduleConfirmGroupSessionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez modifier vos disponibilités pour ce rendez-vous à l&apos;aide de ce calendrier..
        /// </summary>
        public static string ViewScheduleRdvSectionText {
            get {
                return ResourceManager.GetString("ViewScheduleRdvSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez modifier vos disponibilités à l&apos;aide de ce calendrier..
        /// </summary>
        public static string ViewScheduleSectionText {
            get {
                return ResourceManager.GetString("ViewScheduleSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos disponibilités.
        /// </summary>
        public static string ViewScheduleSectionTitle {
            get {
                return ResourceManager.GetString("ViewScheduleSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string ViewSendButton {
            get {
                return ResourceManager.GetString("ViewSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ses disponibilités.
        /// </summary>
        public static string ViewTutorDetailsArticleTitle {
            get {
                return ResourceManager.GetString("ViewTutorDetailsArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string ViewTutorDetailsButtonReturn {
            get {
                return ResourceManager.GetString("ViewTutorDetailsButtonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails du tuteur.
        /// </summary>
        public static string ViewTutorDetailsHeader {
            get {
                return ResourceManager.GetString("ViewTutorDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations personnelles.
        /// </summary>
        public static string ViewTutorDetailsTable1Head {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable1Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        public static string ViewTutorDetailsTable2Column1 {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable2Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours.
        /// </summary>
        public static string ViewTutorDetailsTable2Column2 {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable2Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aptitudes.
        /// </summary>
        public static string ViewTutorDetailsTable2Head {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable2Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce tuteur ne possède aucune aptitude..
        /// </summary>
        public static string ViewTutorDetailsTable2Row {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable2Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances de groupe assignées.
        /// </summary>
        public static string ViewTutorDetailsTable3Column {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable3Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce tuteur n&apos;a été assigné à aucune séance de groupe..
        /// </summary>
        public static string ViewTutorDetailsTable3Row {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable3Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département.
        /// </summary>
        public static string ViewTutorDetailsTable4Column1 {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable4Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours.
        /// </summary>
        public static string ViewTutorDetailsTable4Column2 {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable4Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aidé.
        /// </summary>
        public static string ViewTutorDetailsTable4Column3 {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable4Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Séances individuelles assignées.
        /// </summary>
        public static string ViewTutorDetailsTable4ColumnTitle {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable4ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce tuteur n&apos;a été assigné à aucune séance individuelle..
        /// </summary>
        public static string ViewTutorDetailsTable5ColumnTitle {
            get {
                return ResourceManager.GetString("ViewTutorDetailsTable5ColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer.
        /// </summary>
        public static string ViewTutorListConfirmButton {
            get {
                return ResourceManager.GetString("ViewTutorListConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des tuteurs inscrits.
        /// </summary>
        public static string ViewTutorListHeader {
            get {
                return ResourceManager.GetString("ViewTutorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refuser.
        /// </summary>
        public static string ViewTutorListRefuseButton {
            get {
                return ResourceManager.GetString("ViewTutorListRefuseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mercredi.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
